### ISSUE TITLE
Does this project use purgeCSS to remove unused classes?

### ISSUE THREAD

**Issue by justbrown1980** [hta218/shopify-theme-starter#2]
Does this project use purgecss or some other modification process to purge unused CSS classes after development? Couldn't find a tailwind.config.js so wasn't sure...

**Comment by hta218** [comment]
I've updated the config, now it uses the purge option of tailwind to remove unused CSS

Check the [`tailwind.config.js`](https://github.com/hta218/shopify-theme-starter/blob/main/tailwind.config.js) file to see.
